name: Code Lint Check

on: pull_request

jobs:
  clang-format:
    name: Run clang-format style check only for our 'mummy' code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '17'
        check-path: 'src'

