name: Commit Lint Check

on: pull_request

jobs:
  commitlint:
    name: Validate PR commit title with commit lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6

